services:
  - type: web
    plan: free
    name: amazon-purchase-search
    env: python
    buildCommand: pip install -r requirements_deploy.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
